.DEFAULT_GOAL := pgen_rans_codec_test

include Makefile

PGENRANSCODECOBJ = pgen_rans_codec.o
PGENRANSTESTOBJ = $(PGENRANSCODECOBJ) pgen_rans_codec_test.o
PGENRANSCONTAINEROBJ = pgen_rans_container.o pgen_rans_cpu.o
PGENRANSLIBOBJ = $(PGENRANSCODECOBJ) $(PGENRANSCONTAINEROBJ) \
	pgen_rans_encode.o \
	pgen_rans_reader.o
PGENRANSCONTAINERTESTOBJ = $(PGENRANSCODECOBJ) \
	$(PGENRANSCONTAINEROBJ) pgen_rans_reader.o \
	pgen_rans_container_test.o
PGENRANSTOOLSRC = $(PGENLIB_CCSRC) pgen_rans_codec.cc \
	pgen_rans_container.cc pgen_rans_cpu.cc pgen_rans_encode.cc \
	pgen_rans_tool.cc
PGENRANSTOOLOBJ = $(PGENRANSTOOLSRC:.cc=.o)

# The rANS hot loop benefits measurably from O3 scheduling on
# latency-bound AVX-512 targets.  Keep the rest of PLINK's flags unchanged.
pgen_rans_codec.o: CXXFLAGS += -O3

.PHONY: libpgen_rans pgen_rans pgen_rans_codec_test \
	pgen_rans_container_test test

libpgen_rans: $(PGENRANSLIBOBJ)
	$(MKDIR) -p bin
	$(AR) rcs bin/libpgen_rans.a $(PGENRANSLIBOBJ)

pgen_rans: $(PGENRANSTOOLOBJ)
	$(MKDIR) -p bin
	$(CXX) $(PGENRANSTOOLOBJ) \
		-o bin/pgen_rans $(LDFLAGS)

pgen_rans_codec_test: $(PGENRANSTESTOBJ)
	$(MKDIR) -p bin
	$(CXX) $(PGENRANSTESTOBJ) \
		-o bin/pgen_rans_codec_test $(LDFLAGS)

pgen_rans_container_test: $(PGENRANSCONTAINERTESTOBJ)
	$(MKDIR) -p bin
	$(CXX) $(PGENRANSCONTAINERTESTOBJ) \
		-o bin/pgen_rans_container_test $(LDFLAGS)

test: pgen_rans_codec_test pgen_rans_container_test
	bin/pgen_rans_codec_test
	bin/pgen_rans_container_test

CLEAN += bin/libpgen_rans.a bin/pgen_rans bin/pgen_rans_codec_test \
	bin/pgen_rans_container_test
